from fastapi import APIRouter, Depends, HTTPException, status
from datetime import datetime, timedelta
import os
import json

from schemas.schemas import ReportGenerationRequest, ReportResponse, FirestoreReportGenerationRequest
from routers.firestore_auth import get_current_user
from services.openai_service_simple import HIPAACompliantOpenAIReportGenerator
from services.hybrid_ai_report_generator import HybridAIReportGenerator

router = APIRouter(prefix="/api/v1/reports", tags=["Reports"])

@router.get("/ping")
async def ping():
    """Simple ping endpoint to test connectivity."""
    return {"status": "ok", "message": "Backend is reachable", "timestamp": datetime.utcnow().isoformat()}

@router.get("/test")
async def test_openai_connection():
    """Test endpoint to verify OpenAI API connection and HIPAA compliance setup."""
    try:
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key or api_key == "your_openai_api_key_here":
            return {
                "status": "error",
                "message": "OpenAI API key not configured. Please set OPENAI_API_KEY in your .env file.",
                "configured": False,
                "hipaa_compliant": False
            }
        
        # Test HIPAA de-identification service
        hipaa_available = False
        hipaa_error = "Unknown error"
        
        try:
            from services.hipaa_deidentification import HIPAADeIdentificationService
            hipaa_service = HIPAADeIdentificationService()
            # Test basic functionality
            test_data = {"id": 1, "name": "Test"}
            hipaa_service.de_identify_patient_data(test_data, test_data)
            hipaa_available = True
            hipaa_error = "No error"
        except Exception as e:
            hipaa_available = False
            hipaa_error = str(e)
        
        return {
            "status": "success", 
            "message": "OpenAI API key is configured with HIPAA de-identification",
            "configured": True,
            "hipaa_compliant": hipaa_available,
            "hipaa_service": "HIPAA Safe Harbor de-identification active" if hipaa_available else f"HIPAA service error: {hipaa_error}",
            "api_key_preview": api_key[:10] + "..." if len(api_key) > 10 else "***",
            "compliance_note": "All PHI is de-identified before sending to OpenAI according to HIPAA Safe Harbor guidelines"
        }
    except Exception as e:
        return {
            "status": "error",
            "message": f"OpenAI test failed: {str(e)}",
            "configured": False,
            "hipaa_compliant": False
        }

@router.get("/test-ai")
async def test_ai_generation():
    """Test endpoint to verify OpenAI is actually generating content."""
    try:
        # Create test service (using imported service)
        ai_service = HIPAACompliantOpenAIReportGenerator()
        
        # Simple test prompt
        test_start = datetime.utcnow()
        response = await ai_service.client.chat.completions.create(
            model="o4-mini",
            messages=[
                {
                    "role": "system", 
                    "content": "You are a medical AI assistant. Respond with a brief medical analysis."
                },
                {
                    "role": "user",
                    "content": "Generate a brief medical summary for a de-identified pediatric allergy patient (PATIENT_12345678) with eczema symptoms over the past month. This is test data - no real PHI."
                }
            ],
            temperature=0.3,
            max_tokens=500
        )
        test_end = datetime.utcnow()
        
        if not response.choices or not response.choices[0].message.content:
            return {
                "status": "error",
                "message": "OpenAI returned empty response",
                "ai_working": False
            }
        
        ai_content = response.choices[0].message.content
        processing_time = (test_end - test_start).total_seconds()
        
        return {
            "status": "success",
            "message": "OpenAI o4-mini is generating content successfully",
            "ai_working": True,
            "ai_details": {
                "model_used": "o4-mini",
                "processing_time_seconds": round(processing_time, 2),
                "response_length": len(ai_content),
                "content_preview": ai_content[:200] + "..." if len(ai_content) > 200 else ai_content,
                "full_response": ai_content,
                "timestamp": test_end.isoformat(),
                "temperature": 0.3,
                "max_tokens": 500
            },
            "verification": "This response was generated by OpenAI o4-mini AI in real-time"
        }
        
    except Exception as e:
        return {
            "status": "error", 
            "message": f"AI test failed: {str(e)}",
            "ai_working": False
        }

@router.post("/generate", response_model=ReportResponse)
async def generate_allergy_report(
    request: ReportGenerationRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Generate a comprehensive allergy report using OpenAI API.
    
    The report includes:
    - Patient details and medical history
    - Reaction history with serious reactions prioritized
    - Allergy testing information
    - Diagnosed and suspected allergies
    - Current management plan
    - Planned appointments
    """
    try:
        # Verify child belongs to current user
        child = db.query(Child).filter(
            Child.id == request.child_id,
            Child.parent_id == current_user.id
        ).first()
        
        if not child:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Child not found or access denied"
            )
        
        # Get date range for data collection
        end_date = request.end_date or datetime.utcnow()
        start_date = request.start_date or (end_date - timedelta(days=90))  # Default to 3 months
        
        # Collect comprehensive data
        daily_logs = db.query(DailyLog).filter(
            DailyLog.child_id == request.child_id,
            DailyLog.date >= start_date,
            DailyLog.date <= end_date
        ).order_by(DailyLog.date.desc()).all()
        
        photos = []
        if request.include_photos:
            photos = db.query(PhotoEntry).filter(
                PhotoEntry.child_id == request.child_id,
                PhotoEntry.date >= start_date,
                PhotoEntry.date <= end_date
            ).order_by(PhotoEntry.date.desc()).all()
        
        # Initialize Hybrid AI report generator (combines AI insights with personal data)
        hybrid_service = HybridAIReportGenerator()
        
        # Generate the hybrid report (AI insights + complete personal data)
        report = await hybrid_service.generate_hybrid_report(
            child=child,
            parent=current_user,
            daily_logs=daily_logs,
            photos=photos,
            request=request
        )
        
        return ReportResponse(
            success=True,
            report_text=json.dumps(report, indent=2, default=str)  # Convert dict to JSON string
        )
        
    except Exception as e:
        import traceback
        error_details = f"Failed to generate report: {str(e)}\n\nTraceback:\n{traceback.format_exc()}"
        print(f"❌ Report generation error: {error_details}")
        return ReportResponse(
            success=False,
            error_message=error_details
        )

@router.post("/generate-text", response_model=ReportResponse)
async def generate_text_report(
    request: ReportGenerationRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Generate a structured text-based allergy report using OpenAI API.
    
    Returns a formatted text report suitable for sharing with healthcare providers.
    """
    try:
        # Verify child belongs to current user
        child = db.query(Child).filter(
            Child.id == request.child_id,
            Child.parent_id == current_user.id
        ).first()
        
        if not child:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Child not found or access denied"
            )
        
        # Get date range for data collection
        end_date = request.end_date or datetime.utcnow()
        start_date = request.start_date or (end_date - timedelta(days=90))  # Default to 3 months
        
        # Collect data
        daily_logs = db.query(DailyLog).filter(
            DailyLog.child_id == request.child_id,
            DailyLog.date >= start_date,
            DailyLog.date <= end_date
        ).order_by(DailyLog.date.desc()).all()
        
        # Initialize HIPAA-compliant OpenAI service
        openai_service = HIPAACompliantOpenAIReportGenerator()
        
        # Generate the text report
        report_text = await openai_service.generate_text_report(
            child=child,
            parent=current_user,
            daily_logs=daily_logs,
            request=request
        )
        
        return ReportResponse(
            success=True,
            report_text=report_text
        )
        
    except Exception as e:
        return ReportResponse(
            success=False,
            error_message=f"Failed to generate text report: {str(e)}"
        )

@router.get("/child/{child_id}/summary")
async def get_child_summary(
    child_id: int,
    days: int = 30,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get a quick summary of child's recent allergy data for report generation preview.
    """
    try:
        # Verify child belongs to current user
        child = db.query(Child).filter(
            Child.id == child_id,
            Child.parent_id == current_user.id
        ).first()
        
        if not child:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Child not found or access denied"
            )
        
        # Get recent data
        end_date = datetime.utcnow()
        start_date = end_date - timedelta(days=days)
        
        daily_logs = db.query(DailyLog).filter(
            DailyLog.child_id == child_id,
            DailyLog.date >= start_date,
            DailyLog.date <= end_date
        ).all()
        
        # Calculate summary statistics
        total_logs = len(daily_logs)
        
        # Count symptoms and triggers
        all_symptoms = []
        all_triggers = []
        severe_reactions = 0
        
        for log in daily_logs:
            if log.symptoms:
                if isinstance(log.symptoms, str):
                    symptoms = json.loads(log.symptoms) if log.symptoms else []
                else:
                    symptoms = log.symptoms or []
                all_symptoms.extend(symptoms)
            
            if log.triggers:
                if isinstance(log.triggers, str):
                    triggers = json.loads(log.triggers) if log.triggers else []
                else:
                    triggers = log.triggers or []
                all_triggers.extend(triggers)
            
            # Check for severe reactions (simplified logic)
            if (log.eczema_severity in ['severe', 'very_severe'] or 
                log.asthma_severity in ['severe', 'very_severe'] or
                log.allergic_reaction_severity in ['severe', 'very_severe']):
                severe_reactions += 1
        
        # Count unique items
        unique_symptoms = list(set(all_symptoms))
        unique_triggers = list(set(all_triggers))
        
        return {
            "child_name": child.name,
            "summary_period_days": days,
            "total_log_entries": total_logs,
            "unique_symptoms": unique_symptoms,
            "unique_triggers": unique_triggers,
            "severe_reactions_count": severe_reactions,
            "known_allergies": json.loads(child.known_allergies) if child.known_allergies else [],
            "current_medications": json.loads(child.medications) if child.medications else [],
            "medical_conditions": json.loads(child.medical_conditions) if child.medical_conditions else []
        }
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get child summary: {str(e)}"
        )

@router.post("/test-generate")
async def test_generate_report(
    request: ReportGenerationRequest,
    db: Session = Depends(get_db)
):
    """
    Test endpoint for report generation without authentication.
    """
    try:
        print(f"🔍 Testing report generation for child_id: {request.child_id}")
        
        # Check if child exists (without user verification)
        child = db.query(Child).filter(Child.id == request.child_id).first()
        
        if not child:
            # Create a test child if none exists
            print(f"❌ Child {request.child_id} not found, creating test child...")
            test_user = db.query(User).first()
            if not test_user:
                # Create a test user
                test_user = User(
                    id=1,
                    email="test@example.com",
                    full_name="Test User",
                    hashed_password="testpassword"  # Simple password for testing
                )
                db.add(test_user)
                db.flush()
                
            child = Child(
                id=request.child_id,
                name="projects/allergyapp-1a030/databases/(default)/documents/children/child_1751823814217_1wjfre4n6",
                date_of_birth=datetime.utcnow() - timedelta(days=365*5),  # 5 years old
                parent_id=test_user.id,
                gender="Unknown",
                known_allergies='["Peanuts", "Tree nuts", "Shellfish"]',
                medications='["EpiPen", "Antihistamine"]',
                medical_conditions='["Allergic rhinitis", "Eczema", "Food allergies"]'
            )
            db.add(child)
            db.commit()
            print(f"✅ Created test child with realistic data: {child.name}")
        
        # Get date range for data collection
        end_date = request.end_date or datetime.utcnow()
        start_date = request.start_date or (end_date - timedelta(days=90))
        
        print(f"📅 Date range: {start_date} to {end_date}")
        
        # Collect data
        daily_logs = db.query(DailyLog).filter(
            DailyLog.child_id == request.child_id,
            DailyLog.date >= start_date,
            DailyLog.date <= end_date
        ).order_by(DailyLog.date.desc()).all()
        
        print(f"📊 Found {len(daily_logs)} daily logs")
        
        # Create some test logs if none exist
        if not daily_logs:
            print("Creating test daily logs...")
            for i in range(5):
                test_log = DailyLog(
                    child_id=request.child_id,
                    date=datetime.utcnow() - timedelta(days=i),
                    symptoms=["runny nose", "itchy eyes", "eczema flare"],  # JSON array
                    symptom_severity={"runny_nose": 3, "itchy_eyes": 2, "eczema": 4},  # JSON object
                    triggers=["pollen", "dust"],  # JSON array
                    mood="good",
                    mood_scale=7,
                    general_notes=f"Test notes for day {i+1}",
                    parent_observations=f"Parent observed symptoms on day {i+1}"
                )
                db.add(test_log)
            db.commit()
            
            # Re-fetch logs
            daily_logs = db.query(DailyLog).filter(
                DailyLog.child_id == request.child_id,
                DailyLog.date >= start_date,
                DailyLog.date <= end_date
            ).order_by(DailyLog.date.desc()).all()
            print(f"✅ Created {len(daily_logs)} test daily logs")
        
        photos = []
        if request.include_photos:
            photos = db.query(PhotoEntry).filter(
                PhotoEntry.child_id == request.child_id,
                PhotoEntry.date >= start_date,
                PhotoEntry.date <= end_date
            ).order_by(PhotoEntry.date.desc()).all()
        
        print(f"📷 Found {len(photos)} photos")
        
        # Initialize HIPAA-compliant OpenAI service
        print("🤖 Initializing AI service...")
        openai_service = HIPAACompliantOpenAIReportGenerator()
        
        # Create a test user for the parent
        test_parent = User(
            id=999,
            email="test@example.com",
            full_name="Test Parent",
            hashed_password="test"
        )
        
        # Generate the report
        print("🤖 Generating AI report...")
        report = await openai_service.generate_comprehensive_report(
            child=child,
            parent=test_parent,
            daily_logs=daily_logs,
            photos=photos,
            request=request
        )
        
        print("✅ AI report generated successfully")
        
        return ReportResponse(
            success=True,
            report_text=json.dumps(report, indent=2, default=str)
        )
        
    except Exception as e:
        print(f"❌ Error in test report generation: {str(e)}")
        import traceback
        traceback.print_exc()
        return ReportResponse(
            success=False,
            error_message=f"Test generation failed: {str(e)}"
        )

@router.post("/generate-firestore")
async def generate_firestore_report(
    request: FirestoreReportGenerationRequest
):
    """
    Generate a comprehensive allergy report using Firestore data and OpenAI API.
    This endpoint works with Firestore collections instead of SQLAlchemy.
    """
    try:
        print(f"🔍 Generating Firestore report for child_id: {request.child_id}")
        print(f"📅 Request parameters:")
        print(f"   start_date: {request.start_date}")
        print(f"   end_date: {request.end_date}")
        print(f"   include_ai_insights: {getattr(request, 'include_ai_insights', 'Not set')}")
        print(f"   days_back: {getattr(request, 'days_back', 'Not set')}")
        
        # Initialize Firebase/Firestore
        from config.firebase_config import get_firestore_client
        db = get_firestore_client()
        
        # Extract child document ID from the Firestore path
        child_doc_id = request.child_id
        if isinstance(child_doc_id, str) and "/" in child_doc_id:
            # Extract the actual document ID from the path
            # "projects/allergyapp-1a030/databases/(default)/documents/children/child_1751823814217_1wjfre4n6"
            child_doc_id = child_doc_id.split("/")[-1]
        
        print(f"📄 Using child document ID: {child_doc_id}")
        
        # Get child data from Firestore
        child_ref = db.collection('children').document(str(child_doc_id))
        child_doc = child_ref.get()
        
        if not child_doc.exists:
            print(f"❌ Child document {child_doc_id} not found in Firestore")
            return ReportResponse(
                success=False,
                error_message=f"Child document {child_doc_id} not found in Firestore database"
            )
        
        child_data = child_doc.to_dict() or {}
        print(f"✅ Found child: {child_data.get('first_name', 'Unknown')} {child_data.get('last_name', 'Child')}")
        
        # Debug print child data fields
        print("Child data fields:")
        for key, value in child_data.items():
            if len(str(value)) < 100:  # Only show shorter values
                print(f"  {key}: {value} ({type(value)})")
        
        
        # Get daily logs from Firestore (simplified query to avoid index requirements)
        logs_ref = db.collection('dailyLogs').where('childId', '==', str(child_doc_id)).limit(50)
        
        # Note: For production, you would create the required Firestore composite index
        # or implement client-side filtering for date ranges
        
        daily_logs_docs = logs_ref.get()
        daily_logs_data = []
        total_logs_before_filtering = len(daily_logs_docs)
        
        print(f"📊 Retrieved {total_logs_before_filtering} logs from Firestore before filtering")
        
        for doc in daily_logs_docs:
            log_data = doc.to_dict() or {}
            log_data['id'] = doc.id
            
            # Client-side date filtering if dates are provided
            if request.start_date or request.end_date:
                log_date_str = log_data.get('date', '')
                print(f"   Log {doc.id}: date={log_date_str}")
                
                if log_date_str:
                    try:
                        from datetime import timezone
                        log_date = datetime.fromisoformat(log_date_str.replace('Z', '+00:00'))
                        
                        # Make sure we're comparing dates properly - convert to date-only comparison if needed
                        if request.start_date:
                            start_with_tz = request.start_date
                            if start_with_tz.tzinfo is None:
                                start_with_tz = start_with_tz.replace(tzinfo=timezone.utc)
                            
                            # Compare just the date portion to be more lenient
                            log_date_only = log_date.date()
                            start_date_only = start_with_tz.date()
                            
                            print(f"     Checking start_date: {log_date_only} >= {start_date_only}")
                            if log_date_only < start_date_only:
                                print(f"     ❌ Filtered out: log date {log_date_only} is before start date {start_date_only}")
                                continue
                                
                        if request.end_date:
                            end_with_tz = request.end_date
                            if end_with_tz.tzinfo is None:
                                end_with_tz = end_with_tz.replace(tzinfo=timezone.utc)
                            
                            # Compare just the date portion to be more lenient
                            log_date_only = log_date.date()
                            end_date_only = end_with_tz.date()
                            
                            print(f"     Checking end_date: {log_date_only} <= {end_date_only}")
                            if log_date_only > end_date_only:
                                print(f"     ❌ Filtered out: log date {log_date_only} is after end date {end_date_only}")
                                continue
                                
                        print(f"     ✅ Log passed date filter")
                    except (ValueError, TypeError, ImportError) as e:
                        print(f"     ❌ Error parsing date {log_date_str}: {e}")
                        continue
                else:
                    print(f"     ⚠️ No date in log, skipping")
                    continue
            else:
                print(f"   Log {doc.id}: no date filtering applied")
            
            daily_logs_data.append(log_data)
        
        print(f"📊 Found {len(daily_logs_data)} daily logs after filtering (started with {total_logs_before_filtering})")
        
        # If no logs found, return an error - only work with real data
        if not daily_logs_data:
            print(f"⚠️ No daily logs found for child {child_doc_id}")
            print("📋 DEBUG INFO:")
            print(f"   Total logs in Firestore: {total_logs_before_filtering}")
            print(f"   Logs after date filtering: {len(daily_logs_data)}")
            print(f"   Start date filter: {request.start_date}")
            print(f"   End date filter: {request.end_date}")
            return ReportResponse(
                success=False,
                error_message=f"No daily logs found for child {child_doc_id} in the specified date range. Please ensure symptom tracking data exists in Firestore for this child and date range."
            )
        
        # Get parent data from Firestore if available
        parent_data = {}
        if child_data.get('parentId'):
            parent_ref = db.collection('parents').document(str(child_data['parentId']))
            parent_doc = parent_ref.get()
            if parent_doc.exists:
                parent_data = parent_doc.to_dict() or {}
                print(f"✅ Found parent: {parent_data.get('fullName', 'Unknown Parent')}")
            else:
                print(f"⚠️ Parent document {child_data['parentId']} not found")
        
        # Convert Firestore data to format expected by AI service
        # Create mock objects that match the SQLAlchemy model structure
        class MockChild:
            def __init__(self, data):
                self.id = child_doc_id
                # Use the correct field names from Firestore
                self.name = f"{data.get('first_name', 'Unknown')} {data.get('last_name', 'Child')}"
                
                # Parse date of birth
                dob_str = data.get('date_of_birth', data.get('dateOfBirth', '2019-01-01'))
                try:
                    if isinstance(dob_str, str):
                        self.date_of_birth = datetime.fromisoformat(dob_str)
                    else:
                        self.date_of_birth = datetime(2019, 1, 1)
                except (ValueError, TypeError):
                    self.date_of_birth = datetime(2019, 1, 1)
                
                self.gender = data.get('gender', 'unknown')
                self.known_allergies = str(data.get('known_allergies', data.get('knownAllergies', [])))
                self.medications = str(data.get('current_medications', data.get('medications', [])))
                self.medical_conditions = str(data.get('medical_conditions', data.get('medicalConditions', [])))
                self.parent_id = data.get('parent_user_id', data.get('parentId', 'unknown'))
        
        class MockParent:
            def __init__(self, parent_data):
                self.id = parent_data.get('id', child_data.get('parentId', 'unknown_parent'))
                self.email = parent_data.get('email', 'unknown@example.com')
                self.full_name = parent_data.get('fullName', parent_data.get('name', 'Unknown Parent'))
                self.phone = parent_data.get('phone', 'Unknown Phone')
        
        class MockDailyLog:
            def __init__(self, data):
                self.id = data.get('id', 'unknown')
                self.child_id = data.get('childId')
                
                # Parse date string to datetime object
                date_str = data.get('date', '')
                try:
                    if isinstance(date_str, str):
                        # Handle ISO format dates
                        self.date = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
                    else:
                        self.date = datetime.utcnow()
                except (ValueError, TypeError):
                    self.date = datetime.utcnow()
                
                self.symptoms = data.get('symptoms', [])
                self.symptom_severity = data.get('symptomSeverity', {})
                # Handle case where symptom_severity might be a number or other type
                if not isinstance(self.symptom_severity, dict):
                    self.symptom_severity = {}
                self.triggers = data.get('triggers', [])
                self.mood = data.get('mood', 'unknown')
                mood_scale_raw = data.get('moodScale', 5)
                # Ensure mood_scale is a number
                if isinstance(mood_scale_raw, (int, float)):
                    self.mood_scale = mood_scale_raw
                elif isinstance(mood_scale_raw, str) and mood_scale_raw.isdigit():
                    self.mood_scale = int(mood_scale_raw)
                else:
                    self.mood_scale = 5  # default value
                self.general_notes = data.get('generalNotes', '')
                self.parent_observations = data.get('parentObservations', '')
                self.eczema_severity = data.get('eczemaSeverity', 'mild')
                self.asthma_severity = data.get('asthmaSeverity', 'mild')
                self.allergic_reaction_severity = data.get('allergicReactionSeverity', 'mild')
        
        # Create mock objects
        mock_child = MockChild(child_data)
        mock_parent = MockParent(parent_data)
        mock_daily_logs = [MockDailyLog(log) for log in daily_logs_data]
        
        print("Initializing Hybrid AI service...")
        
        # Initialize Hybrid AI report generator (combines AI insights with personal data)
        hybrid_service = HybridAIReportGenerator()
        
        # Generate the hybrid report (AI insights + complete personal data)
        print("🤖 Generating hybrid AI report with Firestore data...")
        try:
            report = await hybrid_service.generate_hybrid_report(
                child=mock_child,
                parent=mock_parent,
                daily_logs=mock_daily_logs,
                photos=[],  # No photos for now
                request=request
            )
            print("✅ AI report generated successfully with Firestore data")
        except Exception as e:
            print(f"❌ Error in hybrid service: {str(e)}")
            # Log more details about the error
            import traceback
            print("Full traceback:")
            traceback.print_exc()
            raise e
        
        return ReportResponse(
            success=True,
            report_text=json.dumps(report, indent=2, default=str)
        )
        
    except Exception as e:
        print(f"❌ Error in Firestore report generation: {str(e)}")
        import traceback
        traceback.print_exc()
        return ReportResponse(
            success=False,
            error_message=f"Firestore report generation failed: {str(e)}"
        )

@router.get("/test-hybrid")
async def test_hybrid_ai_generation():
    """Test endpoint to verify the Hybrid AI Report Generator is working."""
    try:
        # Create test hybrid service (using imported service)
        hybrid_service = HybridAIReportGenerator()
        
        print("🧪 Testing hybrid AI report generation...")
        
        # Create minimal test data structures
        class TestChild:
            def __init__(self):
                self.id = "test_child_123"
                self.name = "Test Child"
                self.date_of_birth = datetime(2018, 6, 15)
                self.gender = "unknown"
                self.known_allergies = '["Peanuts", "Tree nuts"]'
                self.medications = '["EpiPen", "Benadryl"]'
                self.medical_conditions = '["Food allergies", "Eczema"]'
        
        class TestParent:
            def __init__(self):
                self.id = "test_parent_123"
                self.email = "test.parent@example.com"
                self.full_name = "Test Parent"
        
        class TestDailyLog:
            def __init__(self, day_offset):
                self.id = f"test_log_{day_offset}"
                self.child_id = "test_child_123"
                self.date = datetime.utcnow() - timedelta(days=day_offset)
                self.symptoms = ["runny nose", "itchy eyes", "eczema flare"]
                self.symptom_severity = {"runny_nose": 3, "itchy_eyes": 2, "eczema": 4}
                self.triggers = ["pollen", "dust mites"]
                self.mood = "good"
                self.mood_scale = 7
                self.general_notes = f"Test observations for day {day_offset + 1}"
                self.parent_observations = f"Parent notes for day {day_offset + 1}"
                self.eczema_severity = "moderate"
                self.asthma_severity = "mild"
                self.allergic_reaction_severity = "mild"
        
        class TestRequest:
            def __init__(self):
                self.child_id = "test_child_123"
                self.start_date = datetime.utcnow() - timedelta(days=7)
                self.end_date = datetime.utcnow()
                self.include_photos = False
        
        # Create test objects
        test_child = TestChild()
        test_parent = TestParent()
        test_logs = [TestDailyLog(i) for i in range(5)]  # 5 days of test data
        test_photos = []  # No photos for testing
        test_request = TestRequest()
        
        # Generate hybrid report
        test_start = datetime.utcnow()
        report = await hybrid_service.generate_hybrid_report(
            child=test_child,
            parent=test_parent,
            daily_logs=test_logs,
            photos=test_photos,
            request=test_request
        )
        test_end = datetime.utcnow()
        
        processing_time = (test_end - test_start).total_seconds()
        
        # Validate report structure
        has_ai_insights = "ai_medical_insights" in report
        has_personal_data = "patient_information" in report
        has_detailed_logs = "detailed_daily_logs" in report
        
        patient_name_included = False
        if has_personal_data:
            patient_name_included = report["patient_information"].get("patient_name") == "Test Child"
        
        return {
            "status": "success",
            "message": "Hybrid AI Report Generator is working correctly!",
            "hybrid_working": True,
            "test_details": {
                "total_processing_time_seconds": round(processing_time, 2),
                "report_sections": list(report.keys()),
                "has_ai_insights": has_ai_insights,
                "has_personal_data": has_personal_data,
                "has_detailed_logs": has_detailed_logs,
                "patient_name_included": patient_name_included,
                "ai_model_used": report.get("report_generation", {}).get("ai_component", "Unknown"),
                "generation_method": report.get("report_generation", {}).get("method", "Unknown"),
                "hipaa_compliant": report.get("report_generation", {}).get("hipaa_compliant", False),
                "contains_phi": report.get("report_generation", {}).get("contains_phi", False)
            },
            "sample_ai_insight": report.get("ai_medical_insights", {}).get("analysis", "")[:300] + "..." if report.get("ai_medical_insights", {}).get("analysis") else "No AI insight generated",
            "verification": "This hybrid report contains AI-generated medical insights merged with complete personal data"
        }
        
    except Exception as e:
        import traceback
        error_details = traceback.format_exc()
        print(f"❌ Hybrid AI test error: {error_details}")
        return {
            "status": "error", 
            "message": f"Hybrid AI test failed: {str(e)}",
            "hybrid_working": False,
            "error_details": error_details
        }
